language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"

# Travis doesn't support PostgreSQL 9.5 yet:
#services:
#    - postgresql
#addons:
#    postgresql: "9.5"

# Custom PostgreSQL 9.5:
sudo: required
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get remove --purge postgresql-9.2 postgresql-9.3 postgresql-9.4
  - sudo apt-get install postgresql-9.5


before_script:
    - psql -c 'create database test_libtree;' -U postgres -h localhost
install:
    - pip install .
    - pip install coveralls pytest-cov
script:
    - make unit
after_success:
    - coveralls
