language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy3"
services:
    - postgresql
addons:
    postgresql: "9.4"
before_script:
    - psql -c 'create database test_libtree;' -U postgres
install:
    - pip install .
    - pip install coveralls pytest-cov
script:
    - make unit
after_success:
    - coveralls
