language: python
python:
    - "2.7"
    - "3.4"
#    - "pypy3"
services:
    - postgresql
addons:
    postgresql: "9.4"
before_script:
  - psql -c 'create database test_libtree;' -U postgres
install:
    - pip install .
script:
    - py.test -v tests
