language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"

# Travis doesn't support PostgreSQL 9.5 yet:
#services:
#    - postgresql
#addons:
#    postgresql: "9.5"

# Custom PostgreSQL 9.5:
sudo: required
env:
    - PGPORT=5433 PGHOST=localhost
addons:
    apt:
        sources:
            - precise-pgdg-9.5
        packages:
            - postgresql-9.5
            - postgresql-contrib-9.5
    postgresql: 9.5

before_script:
    - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
    - sudo /etc/init.d/postgresql restart
    - psql -c 'create database test_libtree;' -U postgres
install:
    - pip install .
    - pip install coveralls pytest-cov
script:
    - make unit
after_success:
    - coveralls
